name: landing_page
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/Icon-blue-gradient.png
    - assets/telecom.jpg
    - assets/Icon-orange-yellow.png
    - assets/Icon-orange.png
    - assets/GRC Logo.png
    - assets/americantower_logo.jpg
    - assets/atc_monopole_tower.jpg
    - assets/atc_self-support_tower.jpg

    - assets/Googleplay.png

  fonts:
    - family: IBM Plex Mono
      fonts:
        - asset: assets/fonts/IBMPlexMono-Regular.ttf
        - asset: assets/fonts/IBMPlexMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexMono-Italic.ttf
          style: italic