name: Build and Deploy Flutter Web App to Netlify

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true  # Force the use of Node.js 20

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Step 3: Install Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Build the Flutter web app
      - name: Build Flutter web
        run: flutter build web

      # Step 5: Upload build files as artifact (optional)
      - name: Upload Build as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-web-build
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true  # Force the use of Node.js 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js 20 for Netlify CLI
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 6: Install Netlify CLI
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      # Step 7: Deploy to Netlify
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          netlify deploy --prod --dir=build/web --site=$NETLIFY_SITE_ID
