name: Build and Deploy Flutter Web App to Netlify

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Step 3: Install Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Build the Flutter web app
      - name: Build Flutter web
        run: flutter build web

      # Step 5: Upload built web app as artifact (optional, helpful for debugging)
      - name: Upload build as artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-web-build
          path: build/web

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (required for Netlify CLI)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Use Node.js 20

      # Step 3: Install Netlify CLI
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      # Step 4: Deploy to Netlify
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --dir=build/web --prod --site=$NETLIFY_SITE_ID
